---
# tasks file for jira

- name: Install mysql (mariadb and jdbc connector)
  yum: name={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb
    - mysql-connector-java
    - MySQL-python
    - mod_ssl

- name: Enable mysql service
  service: name=mariadb state=started enabled=yes

- name: Set root user pass for mysql
  mysql_user: login_user=root login_password={{ mysql_conf['dbusers']['root']['password'] }} user={{ mysql_conf['dbusers']['root']['username'] }} password={{ mysql_conf['dbusers']['root']['password'] }}

- name: Drop test db
  mysql_db: login_user=root login_password={{ mysql_conf['dbusers']['root']['password'] }} name=test state=absent

- name: Create jiradb
  run_once: true
  mysql_db: login_user=root login_password={{ mysql_conf['dbusers']['root']['password'] }} name=jiradb state=present

- name: Create jiradb user/grants
  run_once: true
  mysql_user: login_user=root login_password={{ mysql_conf['dbusers']['root']['password'] }} user={{ mysql_conf['dbusers']['jiradb']['username'] }} password={{ mysql_conf['dbusers']['jiradb']['password'] }} priv="jiradb.*:ALL" state=present

- name: Download jira product
  get_url: url=http://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-6.3.11-x64.bin dest=/var/tmp/atlassian-jira-6.3.11-x64.bin mode=755

- name: Provide response file template for jira install
  template: src=response.varfile.j2 dest=/var/tmp/response.varfile

- name: Run the jira installer
  command: /var/tmp/atlassian-jira-6.3.11-x64.bin -q -varfile /var/tmp/response.varfile creates=/opt/atlassian/jira

- name: Remove jira init.d file as we provide service unit next
  file: path=/etc/init.d/jira state=absent

- name: Provide jira systemd unit file from template
  template: src=jira.service.j2 dest=/usr/lib/systemd/system/jira.service
  notify:
    - reload systemd
    - restart jira

- name: Remove httpd/conf.d/ssl.conf
  file: path=/etc/httpd/conf.d/ssl.conf state=absent

- name: Provide SSL cert
  file: src=wildcard.pem dest=/etc/ssl/certs/wildcard.pem

- name: Enable httpd proxy front for jira
  template: src=jira.conf.j2 dest=/etc/httpd/conf.d/jira.conf owner=root group=root mode=644
  notify: restart httpd

- name: Enable ajp port 8009 server.xml template for jira
  template: src=server.xml.j2 dest=/opt/atlassian/jira/conf/server.xml owner=root group=root mode=644
  notify: restart jira

- name: Enable jira service
  service: name=jira enabled=yes

- name: Copy dbconfig.xml template for jira (mysql connection)
  template: src=dbconfig.xml.j2 dest=/var/atlassian/application-data/jira/dbconfig.xml owner=jira group=jira
  notify:
    - restart jira

- name: Add limits.conf.j2 template
  template: src=limits.conf.j2 dest=/etc/security/limits.conf owner=root group=root mode=644
