---
galaxy_info:
  author: Patrick Galbraith
  author: Steven Acres
  description: An ansible role for Galera/Percona XtraDB Cluster
  company: SwattekSystems
  license: Apache 2.0
  min_ansible_version: 1.7
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - database
  - packaging
dependencies: []
